# Generated by Django 5.0.3 on 2024-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='consored_number',
        ),
    ]
