# Generated by Django 5.0.3 on 2024-06-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
    ]
