# Generated by Django 5.0.3 on 2024-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_censored_number_card_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='censored_number',
            field=models.CharField(default='000000******0000', editable=False, max_length=16),
        ),
    ]
