# Generated by Django 5.0.3 on 2024-06-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_censored_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='censored_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
    ]
